version: "3.7"

services:
  mysqldb:
    image: mysql
    container_name: db_igniteteams
    restart: always
    env_file: ./.env
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      - MYSQL_USER=$MYSQLDB_USER
      - MYSQL_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_NAME=$MYSQLDB_DATABASE
      - MYSQL_PORT=$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql

  app:
    build: .
    container_name: igniteteams
    env_file: ./.env
    ports:
      - $SERVER_PORT:$SERVER_PORT
    volumes:
      - .:/usr/app
    depends_on:
      - mysqldb

volumes:
  db:
